services:
  db:
    image: postgres:latest
    container_name: git-jib-hunter-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: git-jib-hunter-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    name: git-jib-hunter-db-volume
    driver: local
